version: '3'
services:
  db:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  yourls:
    container_name: yourls
    depends_on:
      - db
    ports:
      - ${YOURLS_EXTERNAL_PORT}:${YOURLS_INTERNAL_PORT}
    environment:
      - YOURLS_SITE=${YOURLS_SITE}
      - YOURLS_USER=${YOURLS_USER}
      - YOURLS_PASS=${YOURLS_PASS}
      - YOURLS_DB_HOST=db
      - YOURLS_DB_NAME=${MYSQL_DATABASE}
      - YOURLS_DB_USER=${MYSQL_USER}
      - YOURLS_DB_PASS=${MYSQL_PASSWORD}
      - YOURLS_LANG=${YOURLS_LANG}
      - YOURLS_HOURS_OFFSET=${YOURLS_HOURS_OFFSET}
    image: yourls
    volumes:
      - ./config/config.php:/var/www/html/user/config.php
      - ./config/languages/ja_JP.mo:/var/www/html/user/languages/ja_JP.mo
